### ISSUE TITLE
Illegal reflective access and other errors

### ISSUE THREAD

**Issue by ayaankazerouni** [LaurentTho3/ExtendedPitest#1]
Hello! I have followed the instructions at the README, and downloaded the following jars from the repository:
* pitestPlus.jar
* pitest-ant.jar
* pitest-command-line.jar

Unless I'm mistaken, these are drop-in replacements for the jars I might obtain from, say, Maven central. I am running into some warnings and errors that I hope you can help me with.

**Warning**: An illegal reflective access operation has occurred. Illegal reflective access by org.pitest.reloc.xstream.converters.collections.TreeMapConverter.

**Error**: I'm also getting an exception, and the first few lines of the stack trace are below:
```
Exception in thread "main" java.lang.IllegalArgumentException
	at org.pitest.reloc.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.classinfo.ClassInfoVisitor.getClassInfo(ClassInfoVisitor.java:41)
	at org.pitest.classinfo.Repository.nameToClassInfo(Repository.java:69)
	at org.pitest.classinfo.Repository.fetchClass(Repository.java:59)
	at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:15)
	at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:6)
```

Any help or pointers on how to proceed are appreciated. For example, are there any other dependencies required? I know that previous versions of PIT required `commons-codec` and `xstream` to work. I have tried added these dependencies and still see the above exception.

Thanks!

**Comment by LaurentTho3** [comment]
Hi,

You are right that the JARs are drop-in replacements for the ones you could find in Maven. If I remember well, the version of 

The warning is not linked to the extended operators, but to changes in recent versions of Java. It is only a warning and should not interfere with the results.

Concerning the error, a complete stack trace would be helpful in determining what the root cause is.

An easy solution might be to simply rebuilt a more recent version of PIT with the added operators. A version of the code with the operators integrated can be found here: https://github.com/LaurentTho3/pitest/tree/extended-operators

Hope this helps,
Thomas.

**Comment by ayaankazerouni** [comment]
Rebuilding PIT with the version from hcoles/pitest#533 sounds like a good idea.

Here's the complete stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException
	at org.pitest.reloc.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.classinfo.ClassInfoVisitor.getClassInfo(ClassInfoVisitor.java:41)
	at org.pitest.classinfo.Repository.nameToClassInfo(Repository.java:69)
	at org.pitest.classinfo.Repository.fetchClass(Repository.java:59)
	at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:15)
	at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:6)
	at org.pitest.functional.FCollection.flatMapTo(FCollection.java:56)
	at org.pitest.functional.FCollection.flatMap(FCollection.java:66)
	at org.pitest.classpath.CodeSource.getCode(CodeSource.java:46)
	at org.pitest.mutationtest.verify.DefaultBuildVerifier.verify(DefaultBuildVerifier.java:31)
	at org.pitest.mutationtest.tooling.MutationCoverage.verifyBuildSuitableForMutationTesting(MutationCoverage.java:207)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:110)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:101)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:72)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
```

Thanks for helping out!

**Comment by ayaankazerouni** [comment]
> An easy solution might be to simply rebuilt a more recent version of PIT with the added operators.

This worked. Thanks!
